
# <img alt="NumPy" src="https://upload.wikimedia.org/wikipedia/commons/3/31/NumPy_logo_2020.svg">
## Introduction
[Numpy](https://numpy.org/) is an open source library written in `c++`, It is the fundamental package for `scientific computing with python`.

Numpy provides:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities
- incredible library to perform mathematical and statical operations

Numpy is fast and memory efficiency.In fact, `Tensorflow` and `scikit learn` 
used Numpy array to compute the matrix multiplication in the back end.

- **Website:** https://www.numpy.org
- **Documentation:** https://numpy.org/doc



# How to install Numpy

To install Numpy library, Only prerequisite for installing NumPy is Python itself. If you don’t have Python yet and want the simplest way to get started, we recommend you use the [Anaconda Distribution](https://www.anaconda.com/products/individual)

Please do visit :- https://numpy.org/install/
- NumPy can be installed with `conda`, with `pip`, or with a `package manager` on macOS,windows and Linux.

<u>In remote case</u>, Numpy not installed:
- You can install Numpy using Anaconda:<br>

`conda install -c anaconda numpy`
- in jupyter Notebook:<br>

`
import sys
!conda install --yes --prefix {sys.prefix} numpy
`
- in Virtual environment(pipenv or venv):<br>
    1. Create virtual environment.
    2. Install Numpy using command `pipenv install numpy`.
    3. Start/Run virtual environment.
    4. Check numpy install or not.


# Import Numpy & Check Version

In [1]:
import numpy as np

Above code renames the Numpy namespace to np. This permits us to prefix Numpy function, methods, and attributes with " np " instead of typing " numpy."

### To check the installed version of numpy 

In [2]:
print(np.__version__)

1.19.1


## <u>Python List Vs Numpy</u>

### 1) create 0-D array or scaler.

In [3]:

python_list = 1
print(python_list)

1


In [4]:
#create 0-d array or scaler using numpy.
numpy_array = np.array(1)
print(numpy_array)

#check the dimensions of array
print(numpy_array.ndim,"dimensions Array")

1
0 dimensions Array


### 2) Creating 1-D array 

In [5]:
python_list = [1, 2, 3, 4, 5, 6, 7]
print(python_list)

[1, 2, 3, 4, 5, 6, 7]


In [6]:
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7])
print(numpy_array)
print(numpy_array.ndim,"dimensions Array")

[1 2 3 4 5 6 7]
1 dimensions Array


### 3) Creating 2-D array 

In [7]:
python_list = [[1, 2, 3, 4, 5, 6, 7],
               [8, 9, 10, 11, 12, 13, 14]]
print(python_list)
print(type(python_list))

[[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]]
<class 'list'>


In [8]:
numpy_array = np.array([[1, 2, 3, 4, 5, 6, 7],
                       [8, 9, 10, 11, 12, 13, 14]])
print(numpy_array)

print(numpy_array.ndim,"dimensions Array")

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
2 dimensions Array


### 4) Creating 3-D array 

In [9]:
python_list = [[[1, 2, 3],
                [4, 5, 6]],
               
                [[10, 11, 12],
                 [13, 14, 15]]]
print(python_list)
               

[[[1, 2, 3], [4, 5, 6]], [[10, 11, 12], [13, 14, 15]]]


In [10]:
numpy_array = np.array([[[1, 2, 3],
                        [4, 5, 6]],
                        
                       [[10, 11, 12],
                       [13, 14, 15]]])
print(numpy_array)

print(numpy_array.ndim,"dimensions Array")

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]]
3 dimensions Array


### 5) Empty array

In [11]:
python_list = []
print(python_list)

[]


In [12]:
numpy_array = np.empty((2, 3))
print(numpy_array)

[[2.78148323e-307 1.89144519e-307 2.11392372e-307]
 [1.37962388e-306 4.22764034e-307 3.11523242e-307]]


**NOTE :-** The values in this array are not set. This way of creating an array is therefore
only useful if the array is filled later in the code.

### 6) Create a Range

In [13]:
python_list = []
for i in range(6):
    python_list.append(i)
print(python_list)

[0, 1, 2, 3, 4, 5]


In [14]:
#using list comprehension
python_list = [i for i in range(6)]
print("using list comprehension : ",python_list)

using list comprehension :  [0, 1, 2, 3, 4, 5]


In [15]:
numpy_array = np.arange(6)
print(numpy_array)

[0 1 2 3 4 5]


### 6.1 Arthimetic Operation in python list

In [16]:
mylist = []
add = []
sub = []
mul = []
div = []
rem = [] 
square = []
floor = []

for i in range(6):
    mylist.append(i)
    add.append(i+10)
    sub.append(i-10)
    mul.append(i*10)
    div.append(i/10)
    rem.append(i%10)
    square.append(i**10)
    floor.append(i//10)

print("Original list\n",mylist)

print("\nAddition:",add)
print("Substraction:",sub)
print("Multiplication:",mul)
print("Division:",div)
print("Reminder",rem)
print("Square :",square)
print("Floor Division:",floor)

python_list_comprehension = [i + 10 for i in range(6)]
print("\nAddition using list comprehension :\n",python_list_comprehension)


Original list
 [0, 1, 2, 3, 4, 5]

Addition: [10, 11, 12, 13, 14, 15]
Substraction: [-10, -9, -8, -7, -6, -5]
Multiplication: [0, 10, 20, 30, 40, 50]
Division: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
Reminder [0, 1, 2, 3, 4, 5]
Square : [0, 1, 1024, 59049, 1048576, 9765625]
Floor Division: [0, 0, 0, 0, 0, 0]

Addition using list comprehension :
 [10, 11, 12, 13, 14, 15]


### 6.2) Arthimetic Operation in numpy

In [17]:
import numpy as np
numpy_array = np.arange(6)
print("Original list\n",numpy_array)

print("\nAddition:",numpy_array + 10)
print("Substraction:",numpy_array - 10)
print("Multiplication:",numpy_array * 10)
print("Division:",numpy_array / 10)
print("Reminder",numpy_array % 10)
print("Square :",numpy_array ** 10)
print("Floor Division:",numpy_array // 10)


Original list
 [0 1 2 3 4 5]

Addition: [10 11 12 13 14 15]
Substraction: [-10  -9  -8  -7  -6  -5]
Multiplication: [ 0 10 20 30 40 50]
Division: [0.  0.1 0.2 0.3 0.4 0.5]
Reminder [0 1 2 3 4 5]
Square : [      0       1    1024   59049 1048576 9765625]
Floor Division: [0 0 0 0 0 0]


**NOTE :-** Dot product (or more generally matrix multiplication) is done with a function

In [18]:
numpy_array.dot(numpy_array)

55

# Sophisticated (broadcasting) functions

`Broadcasting` is more like an automatic array allocation.In java, We have ArrayList which it will automatically expand 
the array size.<br>

`Broadcasting` is more like magically performing the array expansion to perform some arthimetic operation such as addition, substraction etc.

In [19]:
import numpy as np
x = np.array([[0,1,2],
            [3,4,5]])

y = np.array([6,7,8])
print(x.shape)
print(y.shape)
z = x + y
print(z.shape)
print("Addition of x and y is")
print(z)

(2, 3)
(3,)
(2, 3)
Addition of x and y is
[[ 6  8 10]
 [ 9 11 13]]


In above Example, we have 2-D array "x" with 2 rows `for each row` we have 3 columns.<br>First row`[0,1,2]`,second row`[3,4,5]` with `shape(2,3)`.

we have 1-D array "y" with 1 row with 3 columns of data`[6,7,8]`with `shape(3,)`

### <u>Performing Addition Operation:  `z = x + y`</u>

Here 2 different array "x" and "y" having different array size.we can perform addition with the help of "broadcasting" concept.<br>
it can be understood as **`for each row of x, return x[i] + y`**
The final output of `z` will be automatically created with shape of z`(2,3)` and store result of `x + y`

##  1. `shape()` in numpy


`shape()` method is used to find the dimensions of array (i.e rows and columns)

If **shape** of numpy array is `(4,3,2)` means, it's 3-D array.Because the shape itself has 3 values `4`,`3` and `2`.<br>

<u>An array with shape of `(4,3,2)` can be visualize as:</u><br> 
- `four(4)` 2-D array with `[3,2]`.
- For each 2-D array it has `3 rows` and `2 columns`.

In [20]:
#for description of shape use question mark(?)
#np.shape?


In [21]:
x= np.array([
            [[1,2],
             [3,4],
             [5,6]],
    
            [[10,11],
             [12,13],
             [14,15]],
    
            [[100,110],
             [120,130],
             [140,150]],
    
            [[1000,1100],
             [1200,1300],
             [1400,1500]],
    
])

In [22]:
x


array([[[   1,    2],
        [   3,    4],
        [   5,    6]],

       [[  10,   11],
        [  12,   13],
        [  14,   15]],

       [[ 100,  110],
        [ 120,  130],
        [ 140,  150]],

       [[1000, 1100],
        [1200, 1300],
        [1400, 1500]]])

In [23]:
x.shape

(4, 3, 2)

In [24]:
np.shape(np.eye(3))

(3, 3)

In [25]:
#1-D array
np.shape([1, 2])

(2,)

In [26]:
#1-D array 
np.shape([0])

(1,)

In [27]:
#2-D array
np.shape([[3, 4]])

(1, 2)

In [28]:
#Empty array
np.shape(0)

()

In [29]:
a = np.array([(1, 2), (3, 4)], dtype=[('x', 'i4'), ('y', 'i4')])
np.shape(a)

(2,)

### array_like

`array_like` means numpy array or list.It will help to convert to numpy array.

# Some Example of numpy

In [30]:

import numpy as np
a = np.array([[1, 2, 3],
              [10, 11, 12]])


In [31]:
#to get datatype
a.dtype

dtype('int32')

In [32]:
#to get individual item size
a.itemsize

4

In [33]:
#to get total size of array
a.nbytes

24

In [34]:
b = np.array([1.0, 2.0, 3.0], dtype='int32')
print(b)

[1 2 3]


## Accessing/changing specific elements rows, columns, etc

In [35]:
a = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


### 1) Accessing rows

In [36]:
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [37]:
a[1:2]

array([[ 8,  9, 10, 11, 12, 13, 14]])

In [38]:
a[1:]

array([[ 8,  9, 10, 11, 12, 13, 14]])

In [39]:
a[1:10]

array([[ 8,  9, 10, 11, 12, 13, 14]])

In [40]:
a[:10]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [41]:
a[1:]

array([[ 8,  9, 10, 11, 12, 13, 14]])

In [42]:
a[:2]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [43]:
a[:1]

array([[1, 2, 3, 4, 5, 6, 7]])

### if row is not exist it will return empty array

In [44]:
a[2:]

array([], shape=(0, 7), dtype=int32)

In [45]:
a[3:]

array([], shape=(0, 7), dtype=int32)

In [46]:
a[:3]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [47]:
#Display form 0 to 1 row(excluding 1)
a[:1]

array([[1, 2, 3, 4, 5, 6, 7]])

### We can also use Negative Index to access rows

In [48]:
# Last available row
a[-1]

array([ 8,  9, 10, 11, 12, 13, 14])

In [49]:
a[-2]

array([1, 2, 3, 4, 5, 6, 7])

### if index not founds return `out of bounds` as Error !!!

In [50]:
a[3]

IndexError: index 3 is out of bounds for axis 0 with size 2

In [51]:
a[-3]

IndexError: index -3 is out of bounds for axis 0 with size 2

## List slicing in python

In [52]:
b = [[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]]
b[0]

[1, 2, 3, 4, 5, 6, 7]

In [53]:
b[1]

[8, 9, 10, 11, 12, 13, 14]

In [54]:
b[0:6]

[[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]]

In [55]:
b[1:2]

[[8, 9, 10, 11, 12, 13, 14]]

In [56]:
b[1:10]

[[8, 9, 10, 11, 12, 13, 14]]

In [57]:
b[1:]

[[8, 9, 10, 11, 12, 13, 14]]

In [58]:
b[:10]

[[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]]

In [59]:
b[:2]

[[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]]

In [60]:
b[:1]

[[1, 2, 3, 4, 5, 6, 7]]

In [61]:
#to get a specific element[rows, columns]
a[1, 5]

13

In [62]:
#using negative index
a[1, -2]

13

In [63]:
#to get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [64]:
#to get a specific column
a[:, 2]

array([ 3, 10])

### [startindex : endindex : stepsize]

In [65]:
a[0, 1:6:2]

array([2, 4, 6])

In [66]:
a[0, 1:-1:2]

array([2, 4, 6])

In [71]:
a[1, 5] = 20

In [68]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [69]:
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [72]:
a[:, 3] = 10101

In [73]:
print(a)

[[    1     2     5 10101     5     6     7]
 [    8     9     5 10101    12    20    14]]


In [74]:
a[0]

array([    1,     2,     5, 10101,     5,     6,     7])